"""empty message

Revision ID: 161ba00431ec
Revises: 3c846ef1a5c4
Create Date: 2025-12-03 09:36:37.658479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161ba00431ec'
down_revision = '3c846ef1a5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quote_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_category.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['service_subcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote_request')
    # ### end Alembic commands ###
