"""empty message

Revision ID: 3c846ef1a5c4
Revises: 1d0af0e3bb23
Create Date: 2025-12-03 07:00:40.620818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c846ef1a5c4'
down_revision = '1d0af0e3bb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('admin_email', sa.String(length=100), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('admin_pwd', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('admin_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
