"""empty message

Revision ID: 677cae85f81f
Revises: 0504f30abc17
Create Date: 2025-12-10 15:29:24.389506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677cae85f81f'
down_revision = '0504f30abc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.drop_column('contact_status')

    # ### end Alembic commands ###
