"""empty message

Revision ID: 7c1f322cb2b2
Revises: 677cae85f81f
Create Date: 2025-12-10 15:45:34.904347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1f322cb2b2'
down_revision = '677cae85f81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'staff', ['assigned_staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_staff_id')

    # ### end Alembic commands ###
