"""empty message

Revision ID: d620a397976f
Revises: b280da6c1ae7
Create Date: 2025-12-07 07:07:06.728959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd620a397976f'
down_revision = 'b280da6c1ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_subcategory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('service_subcategory_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_category', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_subcategory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_subcategory_ibfk_1'), 'service_category', ['category_id'], ['id'])

    # ### end Alembic commands ###
